# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libv8-dev

## Mac osx
# * brew: v8 (OSX)

after_success:
  - Rscript -e 'covr::codecov()'
